name: dart_fundamentos
description: Academia do Flutter | Dart Fundamentos.
version: 1.0.0
homepage: https://github.com/felipecastrosales/dart-fundamentos

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
