name: dart_fundamentals
description: Dart Fundamentals.
version: 2.0.0
homepage: https://github.com/felipecastrosales/dart_fundamentals

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  http: ^1.2.1

dev_dependencies:
  test: ^1.25.7
